### ISSUE TITLE
Internal Error when adding BOM module with YAML 

### ISSUE THREAD

**Issue by NoeSamaille** [cloud-native-toolkit/ascent-ui#17]
Adding Storage Class module to Turbonomic BOM got internal error:

```yaml
    - name: gitops-storageclass
      alias: storage
      variables:
        - name: name
          value: ibmc-vpc-block-mzr
        - name: provisioner_name
          value: vpc.block.csi.ibm.io
        - name: parameter_list
          value: [{key : "classVersion",value : "1"},{key : "csi.storage.k8s.io/fstype", value : "ext4"}, {key : "encrypted",value : "false"},{key : "profile",value : "10iops-tier"},{key : "sizeRange",value : "[10-2000]GiB]"}]
    - name: gitops-ocp-turbonomic
      dependencies:
        - name: storage_class_name
          ref: storage
```

![2586d300-a75e-11ec-87cb-15e326009eef](https://user-images.githubusercontent.com/19164094/159131861-7830ef7a-894f-467c-b584-2cb65862cb43.png)
